version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    build: ./db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # env_file:
    #   - .env
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    restart: always
    networks:
      - nodejs-network

  app:
    container_name: app
    image: vadzimsh/nestjs-app
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - app:/var/lib/app
      - /var/lib/app/node_modules
    # env_file:
    #   - .env
    depends_on: 
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    restart: always
    networks:
      - nodejs-network

volumes:
  pgdata:
  app:

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge
