version: '3.8'

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    build: ./db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    networks:
      - nodejs-network

  app:
    image: vadzimsh/nestjs-app
    container_name: app
    build: .
    restart: always
    depends_on: 
      - postgres
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - app:/var/lib/app
      - /var/lib/app/node_modules
    environment:
      POSTGRES_HOST: postgres

    networks:
      - nodejs-network

volumes:
  pgdata:
    name: pgdata
  app:
    name: app

networks:
  nodejs-network:
    driver: bridge
