version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    restart: always